export class HotelesDestacados{
    idhotel: number; 
    idmunicipio: number; 
    numhabitacion: number;
    precionoche: number; 
    precionochedoble: number;
    precionochepremium: number;
    descripcion: string;
    condicion: string;
    checkin: string;
    checkout: string;
    imagen: string; 
    nombre: string;
    idzona: number;
    usuarioencargado: string; 
    idusuario: number; 
    imagen_secundaria: string;
    imagen_secundaria2: string;
    condicionesbioseguridad: string;
    promediocalificacion: number;
    direccion: string;
    mensaje: string;
    municipio: string;
    zona: string;
    numMaxPersonas: number;
    tipo: string;
    fecha_despuesde: string;
    fecha_antesde: string;
    numHabitDisponibles: number;
    url : string;
    mensaje2: string;
    mensaje3: string;
    boton: boolean;
}